### ISSUE TITLE
Add revisions workflow

### ISSUE THREAD

**Issue by kphunter** [bcit-ltc/infrastructure-documentation#1]
We want a way to preview new features, bugfixes, etc... before they are merged into the `main` branch. 

The following Azure Marketplace Action [Create Azure Container App Review Revisions](https://github.com/marketplace/actions/create-azure-container-app-review-revisions) might be a way to do this...

The code to paste into the auto-generated (Continuous Integration config from within Azure) GitHub Action file is:
```
- name: Add revision to ACA
  uses: Azure/aca-review-apps@v0.2.0
  id: aca_new_revision
  with:
    resource-group: <YOUR_RESOURCE_GROUP>
    name: <YOUR_CONTAINER_APP_NAME>
    revision-name-suffix: <SHORT_HASH>
    image: <YOUR_CONTAINER_IMAGE>

- name: add new comment to PR
  uses: peter-evans/create-or-update-comment@v2
  with:
    issue-number: ${{ github.event.pull_request.number }}
    body: |
      Revision ${{ env.CONTAINERAPP_NAME }}--${{ env.SHORT_HASH }} is created.
      ${{ steps.aca_new_revision.outputs.app-url }}
```

Let's try it.
